---
title: "Fig3"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Figure 3


## Stats for Figure 3, panel a to c

```{r stats_fig3}
library(ggplot2)
library(ggprism)   # we use ggprism theme
library(ggrepel)

## Load data
load(file = paste0("data_fig2_fig3.RData"))

## subset to rare variants (CNV) and psychiatric disorder (NPD)
in_df_plot = data_fig2_fig3[which(data_fig2_fig3$Type %in% c("NPD-med","NPD-umed")),]

## Absolute effect sizes
in_df_plot[,"abs_es_MeanCT"] = abs(in_df_plot[,"es_MeanCT"])
in_df_plot[,"abs_es_TotalSA"] = abs(in_df_plot[,"es_TotalSA"])


### Stats Figure 3A, and 3B
# fold change and Wilcox ranksum test
test_metric = "abs_es_MeanCT"
fold_change_meanCT = median(in_df_plot[in_df_plot[,"Type"] == "NPD-med",test_metric])/median(in_df_plot[in_df_plot[,"Type"] == "NPD-umed",test_metric])
w1 = wilcox.test(in_df_plot[in_df_plot[,"Type"] == "NPD-med",test_metric],in_df_plot[in_df_plot[,"Type"] == "NPD-umed",test_metric])

test_metric = "abs_es_TotalSA"
fold_change_totalSA = median(in_df_plot[in_df_plot[,"Type"] == "NPD-med",test_metric])/median(in_df_plot[in_df_plot[,"Type"] == "NPD-umed",test_metric])
w2 = wilcox.test(in_df_plot[in_df_plot[,"Type"] == "NPD-med",test_metric],in_df_plot[in_df_plot[,"Type"] == "NPD-umed",test_metric])


p_array = c(w1$p.value,w2$p.value)
p_array_adj = p.adjust(p_array,method = "fdr")

df_fold_change_fig3A_3B = data.frame(metric = c("meanCT","totalSA"),
                            fold_change = round(c(fold_change_meanCT,fold_change_totalSA)),
                            pval = p_array,
                            pval_adj = p_array_adj)

print(df_fold_change_fig3A_3B)


## (OPTIONAL) Stats:  Effect size ratio 
test_metric = "ratio_CT_SA"
# Differences in ratios between CNVs and NPDs
w1 = wilcox.test(in_df_plot[in_df_plot[,"Type"] == "NPD-med",test_metric],in_df_plot[in_df_plot[,"Type"] == "NPD-umed",test_metric])

pvalue_ratio_NPDmed_vs_NPDumed = w1$p.value
print(paste0("Fig 3: Stats comparing the distribution of effect size ratios between NPD-med and NPD-umed, Wilcox ranksum p-value=",pvalue_ratio_NPDmed_vs_NPDumed))


# Shift from a ratio of 1
w1 <- wilcox.test(in_df_plot[in_df_plot[,"Type"] == "NPD-med",test_metric],mu = 1,alternative = "greater")
w2 <- wilcox.test(in_df_plot[in_df_plot[,"Type"] == "NPD-umed",test_metric],mu = 1,alternative = "greater")

median_ratio_NPDmed = median(in_df_plot[in_df_plot[,"Type"] == "NPD-med",test_metric])
median_ratio_NPDumed = median(in_df_plot[in_df_plot[,"Type"] == "NPD-umed",test_metric])

p_array = c(w1$p.value,w2$p.value)
p_array_adj = p.adjust(p_array,method = "fdr")

df_median_es_ratio_fig3x = data.frame(type = c("NPD-medicated","NPD-unmedicated"),
                            median_ratio = c(median_ratio_NPDmed,median_ratio_NPDumed),
                            pval = p_array,
                            pval_adj = p_array_adj)

print(df_median_es_ratio_fig3x)


## Stats: Figure 3 C

w1 = wilcox.test(in_df_plot[in_df_plot[,"Type"] == "NPD-med","abs_es_MeanCT"],in_df_plot[in_df_plot[,"Type"] == "NPD-med","abs_es_TotalSA"],paired = TRUE)

w2 = wilcox.test(in_df_plot[in_df_plot[,"Type"] == "NPD-umed","abs_es_MeanCT"],in_df_plot[in_df_plot[,"Type"] == "NPD-umed","abs_es_TotalSA"],paired = TRUE)

p_array = c(w1$p.value,w2$p.value)
p_array_adj = p.adjust(p_array,method = "fdr")

df_paired_CT_and_SA_comparison_fig3C = data.frame(type = c("NPD-medicated","NPD-unmedicated"),
                            pval = p_array,
                            pval_adj = p_array_adj)

print(df_paired_CT_and_SA_comparison_fig3C)


```

## Plot Figure 3 A: meanCT

```{r fig_3a, echo=FALSE}

col_values_CNV_NPD = c("NPD-med" =  "#d95f02","NPD-umed" = "#7570b3")
input_base_font_size = 16
input_label_font_size = 5


p_boxplot_CT = ggplot(in_df_plot, aes(x = Type, y = abs_es_MeanCT,color=Type)) +
  theme_prism(base_size = input_base_font_size,base_line_size = 0.75)+ 
  geom_violin(draw_quantiles = c(0.5),linetype = "dashed",trim = TRUE) +
  scale_color_manual(values = col_values_CNV_NPD)+
  geom_point(size = 3,position = position_jitter(width = 0.3))+
  geom_text_repel(aes(label=Column),size=input_label_font_size,min.segment.length=0.3,max.overlaps=20)+
  #geom_hline(yintercept = 0.1,linetype="dotted", color="black")+
  annotate("text",x=0.6,y= 0.005, size=input_label_font_size,label = paste("-p: pediatric","\n","-y: young"),hjust = 0)+
  xlab(NULL) + ylab("Effect size (abs)")+
  theme(text = element_text(size=input_base_font_size), axis.text.x =element_text(size=input_base_font_size),axis.text.y =element_text(size=input_base_font_size))+
  theme(axis.line.x = element_blank())+
  scale_y_continuous(trans = "log10",limits = c(0.00295,2.65),position = "left",breaks = c(seq(0.003,0.009,0.001),seq(0.01,0.09,0.01),seq(0.1,0.9,0.1),1,2),labels = c(rep("",7),0.01,rep("",8),0.1,rep("",8),1,""))+   
  theme(plot.margin = margin(0,0,0,0, "cm"))+
  theme(legend.position = "none")

print(p_boxplot_CT)


```

## Plot Figure 3 B: totalSA

```{r fig3b, echo=FALSE}

p_boxplot_SA = ggplot(in_df_plot, aes(x = Type, y = abs_es_TotalSA,color=Type)) +
  theme_prism(base_size = input_base_font_size,base_line_size = 0.75)+ 
  geom_violin(draw_quantiles = c(0.5),linetype = "dashed",trim = TRUE) +
  scale_color_manual(values = col_values_CNV_NPD)+
  geom_point(size = 3,position = position_jitter(width = 0.3))+
  geom_text_repel(aes(label=Column),size=input_label_font_size,min.segment.length=0.3,max.overlaps=20)+
  #geom_hline(yintercept = 0.1,linetype="dotted", color="black")+
  #annotate("text",x=0.6,y= 0.005, size=input_label_font_size,label = paste("-p: pediatric","\n","-y: young"),hjust = 0)+
  xlab(NULL) + ylab("Effect size (abs)")+
  theme(text = element_text(size=input_base_font_size), axis.text.x =element_text(size=input_base_font_size),axis.text.y =element_text(size=input_base_font_size))+
  theme(axis.line.x = element_blank())+
  scale_y_continuous(trans = "log10",limits = c(0.00295,2.65),position = "left",breaks = c(seq(0.003,0.009,0.001),seq(0.01,0.09,0.01),seq(0.1,0.9,0.1),1,2),labels = c(rep("",7),0.01,rep("",8),0.1,rep("",8),1,""))+   
  theme(plot.margin = margin(0,0,0,0, "cm"))+
  theme(legend.position = "none")

print(p_boxplot_SA)


```

## Plot Figure 3 x: Effect size ratio

```{r fig3x, echo=FALSE}

p_boxplot_es_ratio = ggplot(in_df_plot, aes(x = Type, y = ratio_CT_SA,color=Type)) +
  theme_prism(base_size = input_base_font_size,base_line_size = 0.75)+ 
  geom_violin(draw_quantiles = c(0.5),linetype = "dashed",trim = TRUE) +
  scale_color_manual(values = col_values_CNV_NPD)+
  geom_point(size = 3,position = position_jitter(width = 0.3))+
  geom_text_repel(aes(label=Column),size=input_label_font_size,min.segment.length=0.3,max.overlaps=20)+
  geom_hline(yintercept = 1,linetype="dotted", color="black",linewidth = 2)+
  #annotate("text",x=0.6,y= 0.005, size=input_label_font_size,label = paste("-p: pediatric","\n","-y: young"),hjust = 0)+
  xlab(NULL) + ylab("Cohen's d CT / Cohen's d SA ratio")+
  theme(text = element_text(size=input_base_font_size), axis.text.x =element_text(size=input_base_font_size),axis.text.y =element_text(size=input_base_font_size))+
  theme(axis.line.x = element_blank())+
  scale_y_continuous(trans = "log10",position = "left",limits = c(0.045,41.5),breaks = c(seq(0.05,0.09,0.01),seq(0.1,0.9,0.1),seq(1,9,1),10,20,30,40),labels = c(0.05,rep("",4),0.1,rep("",8),1,rep("",8),10,rep("",3)))+  
  theme(plot.margin = margin(0,0,0,0, "cm"))+
  theme(legend.position = "none") 
  
print(p_boxplot_es_ratio)


```

## Plot Figure 3 C: Paired boxplots for meanCT and totalSA comparison

```{r fig3c, echo=FALSE}


library(ggpubr)
library(ggsignif)

col_values_metric = c("CT" = "#e41a1c", "SA" = "#377eb8")

## function to make ggpaired plot
ggpaired_boxplot = function(in_df_ggpaired){
  
  in_df_ggpaired[,"metric"] = factor(in_df_ggpaired[,"metric"],levels =c("CT","SA"))
  
  p_ggpaired = ggpaired(in_df_ggpaired, x = "metric", y = "ES",
           color = "metric", shape="metric",line.color = "gray", line.size = 0.6,palette = "jco")+
    theme_prism(base_size = 24,base_line_size = 0.5) +   
    scale_color_manual(values = col_values_metric)+
    theme(legend.position = "none")+
    scale_y_continuous(trans = "log10",limits = c(0.002,3),breaks = c(seq(0.002,0.009,0.001),seq(0.01,0.09,0.01),seq(0.1,0.9,0.1),1,2,3),labels = c(rep("",8),0.01,rep("",8),0.1,rep("",8),1,"",""))+   
    theme(axis.line.x = element_blank())+
    xlab(NULL) + ylab("Effect size (abs)")
  
  return(p_ggpaired)
  
}


in_df_plot_SA_CT_es = data.frame( Column = c(in_df_plot[,"Column"],in_df_plot[,"Column"]),
                                  Type = c(in_df_plot[,"Type"],in_df_plot[,"Type"]),
                                  metric = c(rep("CT",nrow(in_df_plot)),rep("SA",nrow(in_df_plot))),
                                  ES = c(abs(in_df_plot[,"es_MeanCT"]),abs(in_df_plot[,"es_TotalSA"])))

## NPD-medicated
in_df_ggpaired= in_df_plot_SA_CT_es[which(in_df_plot_SA_CT_es[,"Type"] == "NPD-med"),]
p_paired_boxplot_NPDmed = ggpaired_boxplot(in_df_ggpaired)
print("NPD-medicated paired boxplot between meanCT and totalSA effect sizes (abs)")
print(p_paired_boxplot_NPDmed)

## NPD-unmedicated
in_df_ggpaired= in_df_plot_SA_CT_es[which(in_df_plot_SA_CT_es[,"Type"] == "NPD-umed"),]
p_paired_boxplot_NPDumed = ggpaired_boxplot(in_df_ggpaired)
print("NPD-unmedicated paired boxplot between meanCT and totalSA effect sizes (abs)")
print(p_paired_boxplot_NPDumed)


```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
